<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_graphs"
 *
 * Auto generated by Extension Builder 2019-02-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title'            => 'RKW Graphs',
    'description'      => '',
    'category'         => 'plugin',
    'author'           => 'Christian Dilger',
    'author_email'     => 'c.dilger@addorange.de',
    'state'            => 'beta',
    'internal'         => '',
    'uploadfolder'     => '0',
    'createDirs'       => '',
    'clearCacheOnLoad' => 0,
    'version'          => '9.5.0',
    'constraints'      => [
        'depends'   => [
            'typo3' => '9.5.0-9.5.99'
        ],
        'conflicts' => [],
        'suggests'  => []
    ]
];
